//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionMat
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel
    {
        public personnel()
        {
            this.demande_mat_conso = new HashSet<demande_mat_conso>();
            this.demande_mat_conso1 = new HashSet<demande_mat_conso>();
            this.identificateur = new HashSet<identificateur>();
            this.personnel_projet = new HashSet<personnel_projet>();
            this.rese_mat_non_conso = new HashSet<rese_mat_non_conso>();
            this.rese_mat_non_conso1 = new HashSet<rese_mat_non_conso>();
            this.mat_non_conso = new HashSet<mat_non_conso>();
            this.mat_conso = new HashSet<mat_conso>();
        }
    
        public int id_personnel { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string adresse { get; set; }
        public Nullable<System.DateTime> date_naissance { get; set; }
        public bool estActif { get; set; }
    
        public virtual ICollection<demande_mat_conso> demande_mat_conso { get; set; }
        public virtual ICollection<demande_mat_conso> demande_mat_conso1 { get; set; }
        public virtual ICollection<identificateur> identificateur { get; set; }
        public virtual ICollection<personnel_projet> personnel_projet { get; set; }
        public virtual ICollection<rese_mat_non_conso> rese_mat_non_conso { get; set; }
        public virtual ICollection<rese_mat_non_conso> rese_mat_non_conso1 { get; set; }
        public virtual ICollection<mat_non_conso> mat_non_conso { get; set; }
        public virtual ICollection<mat_conso> mat_conso { get; set; }
    }
}
