//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMat
{
    using System;
    using System.Collections.Generic;
    
    public partial class demande_mat_conso
    {
        public int id_demande_mat_conso { get; set; }
        public string etat_demande { get; set; }
        public System.DateTime date_utilisation { get; set; }
        public System.DateTime date_demande { get; set; }
        public Nullable<System.DateTime> date_decision { get; set; }
        public int quantite { get; set; }
        public int id_personnel_demande { get; set; }
        public int id_personnel_decision { get; set; }
        public int id_mat_conso { get; set; }
        public int id_projet { get; set; }
    
        public virtual mat_conso mat_conso { get; set; }
        public virtual personnel personnel { get; set; }
        public virtual personnel personnel1 { get; set; }
        public virtual projet projet { get; set; }
    }
}
