//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMat
{
    using System;
    using System.Collections.Generic;
    
    public partial class identificateur
    {
        public int id_identificateur { get; set; }
        public string login { get; set; }
        public string mdp { get; set; }
        public string profil { get; set; }
        public bool actif { get; set; }
        public int id_personnel { get; set; }
    
        public virtual personnel personnel { get; set; }
    }
}
