//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMat
{
    using System;
    using System.Collections.Generic;
    
    public partial class mat_conso
    {
        public mat_conso()
        {
            this.demande_mat_conso = new HashSet<demande_mat_conso>();
            this.personnel = new HashSet<personnel>();
        }
    
        public int id_mat_conso { get; set; }
        public string nom { get; set; }
        public string code_barres { get; set; }
        public int id_site_de_stockage { get; set; }
    
        public virtual ICollection<demande_mat_conso> demande_mat_conso { get; set; }
        public virtual site_de_stockage site_de_stockage { get; set; }
        public virtual ICollection<personnel> personnel { get; set; }
    }
}
