//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gest_matEntities : DbContext
    {
        public gest_matEntities()
            : base("name=gest_matEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<demande_mat_conso> demande_mat_conso { get; set; }
        public DbSet<identificateur> identificateur { get; set; }
        public DbSet<mat_conso> mat_conso { get; set; }
        public DbSet<mat_non_conso> mat_non_conso { get; set; }
        public DbSet<personnel> personnel { get; set; }
        public DbSet<personnel_projet> personnel_projet { get; set; }
        public DbSet<projet> projet { get; set; }
        public DbSet<rese_mat_non_conso> rese_mat_non_conso { get; set; }
        public DbSet<salle> salle { get; set; }
        public DbSet<site> site { get; set; }
        public DbSet<site_de_stockage> site_de_stockage { get; set; }
        public DbSet<thematique> thematique { get; set; }
        public DbSet<placer> placer { get; set; }
    }
}
