//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMat
{
    using System;
    using System.Collections.Generic;
    
    public partial class placer
    {
        public int id_mat_conso { get; set; }
        public int id_site_de_stockage { get; set; }
        public int quantite { get; set; }
    
        public virtual mat_conso mat_conso { get; set; }
        public virtual site_de_stockage site_de_stockage { get; set; }
    }
}
