//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMat
{
    using System;
    using System.Collections.Generic;
    
    public partial class projet
    {
        public projet()
        {
            this.demande_mat_conso = new HashSet<demande_mat_conso>();
            this.personnel_projet = new HashSet<personnel_projet>();
            this.rese_mat_non_conso = new HashSet<rese_mat_non_conso>();
            this.thematique = new HashSet<thematique>();
        }
    
        public int id_projet { get; set; }
        public string intitule { get; set; }
        public System.DateTime date_debut { get; set; }
        public System.DateTime date_fin_estimee { get; set; }
        public Nullable<System.DateTime> date_fin_reelle { get; set; }
        public decimal budget { get; set; }
        public string problematique { get; set; }
    
        public virtual ICollection<demande_mat_conso> demande_mat_conso { get; set; }
        public virtual ICollection<personnel_projet> personnel_projet { get; set; }
        public virtual ICollection<rese_mat_non_conso> rese_mat_non_conso { get; set; }
        public virtual ICollection<thematique> thematique { get; set; }
    }
}
