//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMat
{
    using System;
    using System.Collections.Generic;
    
    public partial class salle
    {
        public salle()
        {
            this.mat_non_conso = new HashSet<mat_non_conso>();
        }
    
        public int id_salle { get; set; }
        public string nom { get; set; }
        public int id_site { get; set; }
    
        public virtual ICollection<mat_non_conso> mat_non_conso { get; set; }
        public virtual site site { get; set; }
    }
}
