//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMat
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_de_stockage
    {
        public site_de_stockage()
        {
            this.placer = new HashSet<placer>();
        }
    
        public int id_site_de_stockage { get; set; }
        public string adresse { get; set; }
        public string nom { get; set; }
        public int id_site { get; set; }
    
        public virtual site site { get; set; }
        public virtual ICollection<placer> placer { get; set; }
    }
}
