//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMat
{
    using System;
    using System.Collections.Generic;
    
    public partial class thematique
    {
        public thematique()
        {
            this.projet = new HashSet<projet>();
        }
    
        public int id_thematique { get; set; }
        public string libelle { get; set; }
    
        public virtual ICollection<projet> projet { get; set; }
    }
}
